insert into teams(fifa_code, name, country)
values
  ('USA', 'Estados Unidos', 'Estados Unidos'),
  ('MEX', 'Mexico', 'Mexico'),
  ('CAN', 'Canada', 'Canada'),
  ('JPN', 'Japon', 'Japon'),
  ('NZL', 'Nueva Zelanda', 'Nueva Zelanda'),
  ('IRN', 'Iran', 'Iran'),
  ('ARG', 'Argentina', 'Argentina'),
  ('UZB', 'Uzbekistan', 'Uzbekistan'),
  ('KOR', 'Corea del Sur', 'Corea del Sur'),
  ('JOR', 'Jordania', 'Jordania'),
  ('AUS', 'Australia', 'Australia'),
  ('BRA', 'Brasil', 'Brasil'),
  ('ECU', 'Ecuador', 'Ecuador'),
  ('URU', 'Uruguay', 'Uruguay'),
  ('COL', 'Colombia', 'Colombia'),
  ('PAR', 'Paraguay', 'Paraguay'),
  ('MAR', 'Marruecos', 'Marruecos'),
  ('TUN', 'Tunez', 'Tunez'),
  ('EGY', 'Egipto', 'Egipto'),
  ('ALG', 'Argelia', 'Argelia'),
  ('GHA', 'Ghana', 'Ghana'),
  ('CPV', 'Cabo Verde', 'Cabo Verde'),
  ('RSA', 'Sudafrica', 'Sudafrica'),
  ('QAT', 'Qatar', 'Qatar'),
  ('ENG', 'Inglaterra', 'Inglaterra'),
  ('KSA', 'Arabia Saudita', 'Arabia Saudita'),
  ('CIV', 'Costa de Marfil', 'Costa de Marfil'),
  ('SEN', 'Senegal', 'Senegal'),
  ('FRA', 'Francia', 'Francia'),
  ('CRO', 'Croacia', 'Croacia'),
  ('POR', 'Portugal', 'Portugal'),
  ('NOR', 'Noruega', 'Noruega'),
  ('NED', 'Paises Bajos', 'Paises Bajos'),
  ('GER', 'Alemania', 'Alemania'),
  ('BEL', 'Belgica', 'Belgica'),
  ('SUI', 'Suiza', 'Suiza'),
  ('ESP', 'Espana', 'Espana'),
  ('AUT', 'Austria', 'Austria'),
  ('SCO', 'Escocia', 'Escocia'),
  ('CUW', 'Curazao', 'Curazao'),
  ('HAI', 'Haiti', 'Haiti'),
  ('PAN', 'Panama', 'Panama'),
  ('SWE', 'Suecia', 'Suecia'),
  ('TUR', 'Turquia', 'Turquia'),
  ('CZE', 'Republica Checa', 'Republica Checa'),
  ('BIH', 'Bosnia y Herzegovina', 'Bosnia y Herzegovina'),
  ('COD', 'RD Congo', 'RD Congo'),
  ('IRQ', 'Irak', 'Irak')
on conflict (fifa_code) do update
set name = excluded.name,
    country = excluded.country,
    updated_at = now();
