[
  {
    "match": 1,
    "date_utc": "2026-06-11",
    "kickoff_utc": "19:00",
    "kickoff_et": "3:00 PM",
    "team_a": "Mexico",
    "team_a_code": "MX",
    "team_a_flag": "🇲🇽",
    "team_b": "South Africa",
    "team_b_code": "ZA",
    "team_b_flag": "🇿🇦",
    "group": "Group A",
    "venue": "Estadio Azteca",
    "city": "Mexico City",
    "host_country": "Mexico"
  },
  {
    "match": 2,
    "date_utc": "2026-06-12",
    "kickoff_utc": "02:00",
    "kickoff_et": "10:00 PM",
    "team_a": "South Korea",
    "team_a_code": "KR",
    "team_a_flag": "🇰🇷",
    "team_b": "Czechia",
    "team_b_code": "CZ",
    "team_b_flag": "🇨🇿",
    "group": "Group A",
    "venue": "Estadio Akron",
    "city": "Guadalajara",
    "host_country": "Mexico"
  },
  {
    "match": 3,
    "date_utc": "2026-06-12",
    "kickoff_utc": "19:00",
    "kickoff_et": "3:00 PM",
    "team_a": "Canada",
    "team_a_code": "CA",
    "team_a_flag": "🇨🇦",
    "team_b": "Bosnia & Herzegovina",
    "team_b_code": "BA",
    "team_b_flag": "🇧🇦",
    "group": "Group B",
    "venue": "BMO Field",
    "city": "Toronto",
    "host_country": "Canada"
  },
  {
    "match": 4,
    "date_utc": "2026-06-13",
    "kickoff_utc": "01:00",
    "kickoff_et": "9:00 PM",
    "team_a": "United States",
    "team_a_code": "US",
    "team_a_flag": "🇺🇸",
    "team_b": "Paraguay",
    "team_b_code": "PY",
    "team_b_flag": "🇵🇾",
    "group": "Group D",
    "venue": "SoFi Stadium",
    "city": "Inglewood",
    "host_country": "USA"
  },
  {
    "match": 5,
    "date_utc": "2026-06-13",
    "kickoff_utc": "19:00",
    "kickoff_et": "3:00 PM",
    "team_a": "Qatar",
    "team_a_code": "QA",
    "team_a_flag": "🇶🇦",
    "team_b": "Switzerland",
    "team_b_code": "CH",
    "team_b_flag": "🇨🇭",
    "group": "Group B",
    "venue": "Levi's Stadium",
    "city": "Santa Clara",
    "host_country": "USA"
  },
  {
    "match": 6,
    "date_utc": "2026-06-13",
    "kickoff_utc": "22:00",
    "kickoff_et": "6:00 PM",
    "team_a": "Brazil",
    "team_a_code": "BR",
    "team_a_flag": "🇧🇷",
    "team_b": "Morocco",
    "team_b_code": "MA",
    "team_b_flag": "🇲🇦",
    "group": "Group C",
    "venue": "MetLife Stadium",
    "city": "East Rutherford",
    "host_country": "USA"
  },
  {
    "match": 7,
    "date_utc": "2026-06-14",
    "kickoff_utc": "01:00",
    "kickoff_et": "9:00 PM",
    "team_a": "Haiti",
    "team_a_code": "HT",
    "team_a_flag": "🇭🇹",
    "team_b": "Scotland",
    "team_b_code": "SCO",
    "team_b_flag": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "group": "Group C",
    "venue": "Gillette Stadium",
    "city": "Foxborough",
    "host_country": "USA"
  },
  {
    "match": 8,
    "date_utc": "2026-06-14",
    "kickoff_utc": "16:00",
    "kickoff_et": "12:00 PM",
    "team_a": "Australia",
    "team_a_code": "AU",
    "team_a_flag": "🇦🇺",
    "team_b": "Türkiye",
    "team_b_code": "TR",
    "team_b_flag": "🇹🇷",
    "group": "Group D",
    "venue": "BC Place",
    "city": "Vancouver",
    "host_country": "Canada"
  },
  {
    "match": 9,
    "date_utc": "2026-06-14",
    "kickoff_utc": "17:00",
    "kickoff_et": "1:00 PM",
    "team_a": "Germany",
    "team_a_code": "DE",
    "team_a_flag": "🇩🇪",
    "team_b": "Curaçao",
    "team_b_code": "CW",
    "team_b_flag": "🇨🇼",
    "group": "Group E",
    "venue": "NRG Stadium",
    "city": "Houston",
    "host_country": "USA"
  },
  {
    "match": 10,
    "date_utc": "2026-06-14",
    "kickoff_utc": "20:00",
    "kickoff_et": "4:00 PM",
    "team_a": "Netherlands",
    "team_a_code": "NL",
    "team_a_flag": "🇳🇱",
    "team_b": "Japan",
    "team_b_code": "JP",
    "team_b_flag": "🇯🇵",
    "group": "Group F",
    "venue": "AT&T Stadium",
    "city": "Arlington",
    "host_country": "USA"
  },
  {
    "match": 11,
    "date_utc": "2026-06-14",
    "kickoff_utc": "23:00",
    "kickoff_et": "7:00 PM",
    "team_a": "Ivory Coast",
    "team_a_code": "CI",
    "team_a_flag": "🇨🇮",
    "team_b": "Ecuador",
    "team_b_code": "EC",
    "team_b_flag": "🇪🇨",
    "group": "Group E",
    "venue": "Lincoln Financial Field",
    "city": "Philadelphia",
    "host_country": "USA"
  },
  {
    "match": 12,
    "date_utc": "2026-06-15",
    "kickoff_utc": "02:00",
    "kickoff_et": "10:00 PM",
    "team_a": "Sweden",
    "team_a_code": "SE",
    "team_a_flag": "🇸🇪",
    "team_b": "Tunisia",
    "team_b_code": "TN",
    "team_b_flag": "🇹🇳",
    "group": "Group F",
    "venue": "Estadio BBVA",
    "city": "Monterrey",
    "host_country": "Mexico"
  },
  {
    "match": 13,
    "date_utc": "2026-06-15",
    "kickoff_utc": "16:00",
    "kickoff_et": "12:00 PM",
    "team_a": "Spain",
    "team_a_code": "ES",
    "team_a_flag": "🇪🇸",
    "team_b": "Cape Verde",
    "team_b_code": "CV",
    "team_b_flag": "🇨🇻",
    "group": "Group H",
    "venue": "Mercedes-Benz Stadium",
    "city": "Atlanta",
    "host_country": "USA"
  },
  {
    "match": 14,
    "date_utc": "2026-06-15",
    "kickoff_utc": "19:00",
    "kickoff_et": "3:00 PM",
    "team_a": "Belgium",
    "team_a_code": "BE",
    "team_a_flag": "🇧🇪",
    "team_b": "Egypt",
    "team_b_code": "EG",
    "team_b_flag": "🇪🇬",
    "group": "Group G",
    "venue": "Lumen Field",
    "city": "Seattle",
    "host_country": "USA"
  },
  {
    "match": 15,
    "date_utc": "2026-06-15",
    "kickoff_utc": "22:00",
    "kickoff_et": "6:00 PM",
    "team_a": "Saudi Arabia",
    "team_a_code": "SA",
    "team_a_flag": "🇸🇦",
    "team_b": "Uruguay",
    "team_b_code": "UY",
    "team_b_flag": "🇺🇾",
    "group": "Group H",
    "venue": "Hard Rock Stadium",
    "city": "Miami Gardens",
    "host_country": "USA"
  },
  {
    "match": 16,
    "date_utc": "2026-06-16",
    "kickoff_utc": "01:00",
    "kickoff_et": "9:00 PM",
    "team_a": "Iran",
    "team_a_code": "IR",
    "team_a_flag": "🇮🇷",
    "team_b": "New Zealand",
    "team_b_code": "NZ",
    "team_b_flag": "🇳🇿",
    "group": "Group G",
    "venue": "SoFi Stadium",
    "city": "Inglewood",
    "host_country": "USA"
  },
  {
    "match": 17,
    "date_utc": "2026-06-16",
    "kickoff_utc": "19:00",
    "kickoff_et": "3:00 PM",
    "team_a": "France",
    "team_a_code": "FR",
    "team_a_flag": "🇫🇷",
    "team_b": "Senegal",
    "team_b_code": "SN",
    "team_b_flag": "🇸🇳",
    "group": "Group I",
    "venue": "MetLife Stadium",
    "city": "East Rutherford",
    "host_country": "USA"
  },
  {
    "match": 18,
    "date_utc": "2026-06-16",
    "kickoff_utc": "22:00",
    "kickoff_et": "6:00 PM",
    "team_a": "Iraq",
    "team_a_code": "IQ",
    "team_a_flag": "🇮🇶",
    "team_b": "Norway",
    "team_b_code": "NO",
    "team_b_flag": "🇳🇴",
    "group": "Group I",
    "venue": "Gillette Stadium",
    "city": "Foxborough",
    "host_country": "USA"
  },
  {
    "match": 19,
    "date_utc": "2026-06-17",
    "kickoff_utc": "01:00",
    "kickoff_et": "9:00 PM",
    "team_a": "Argentina",
    "team_a_code": "AR",
    "team_a_flag": "🇦🇷",
    "team_b": "Algeria",
    "team_b_code": "DZ",
    "team_b_flag": "🇩🇿",
    "group": "Group J",
    "venue": "Arrowhead Stadium",
    "city": "Kansas City",
    "host_country": "USA"
  },
  {
    "match": 20,
    "date_utc": "2026-06-17",
    "kickoff_utc": "04:00",
    "kickoff_et": "12:00 AM",
    "team_a": "Austria",
    "team_a_code": "AT",
    "team_a_flag": "🇦🇹",
    "team_b": "Jordan",
    "team_b_code": "JO",
    "team_b_flag": "🇯🇴",
    "group": "Group J",
    "venue": "Levi's Stadium",
    "city": "Santa Clara",
    "host_country": "USA"
  },
  {
    "match": 21,
    "date_utc": "2026-06-17",
    "kickoff_utc": "17:00",
    "kickoff_et": "1:00 PM",
    "team_a": "Portugal",
    "team_a_code": "PT",
    "team_a_flag": "🇵🇹",
    "team_b": "DR Congo",
    "team_b_code": "CD",
    "team_b_flag": "🇨🇩",
    "group": "Group K",
    "venue": "NRG Stadium",
    "city": "Houston",
    "host_country": "USA"
  },
  {
    "match": 22,
    "date_utc": "2026-06-17",
    "kickoff_utc": "20:00",
    "kickoff_et": "4:00 PM",
    "team_a": "England",
    "team_a_code": "ENG",
    "team_a_flag": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "team_b": "Croatia",
    "team_b_code": "HR",
    "team_b_flag": "🇭🇷",
    "group": "Group L",
    "venue": "AT&T Stadium",
    "city": "Arlington",
    "host_country": "USA"
  },
  {
    "match": 23,
    "date_utc": "2026-06-17",
    "kickoff_utc": "23:00",
    "kickoff_et": "7:00 PM",
    "team_a": "Ghana",
    "team_a_code": "GH",
    "team_a_flag": "🇬🇭",
    "team_b": "Panama",
    "team_b_code": "PA",
    "team_b_flag": "🇵🇦",
    "group": "Group L",
    "venue": "BMO Field",
    "city": "Toronto",
    "host_country": "Canada"
  },
  {
    "match": 24,
    "date_utc": "2026-06-18",
    "kickoff_utc": "02:00",
    "kickoff_et": "10:00 PM",
    "team_a": "Uzbekistan",
    "team_a_code": "UZ",
    "team_a_flag": "🇺🇿",
    "team_b": "Colombia",
    "team_b_code": "CO",
    "team_b_flag": "🇨🇴",
    "group": "Group K",
    "venue": "Estadio Azteca",
    "city": "Mexico City",
    "host_country": "Mexico"
  },
  {
    "match": 25,
    "date_utc": "2026-06-18",
    "kickoff_utc": "16:00",
    "kickoff_et": "12:00 PM",
    "team_a": "Czechia",
    "team_a_code": "CZ",
    "team_a_flag": "🇨🇿",
    "team_b": "South Africa",
    "team_b_code": "ZA",
    "team_b_flag": "🇿🇦",
    "group": "Group A",
    "venue": "Mercedes-Benz Stadium",
    "city": "Atlanta",
    "host_country": "USA"
  },
  {
    "match": 26,
    "date_utc": "2026-06-18",
    "kickoff_utc": "19:00",
    "kickoff_et": "3:00 PM",
    "team_a": "Switzerland",
    "team_a_code": "CH",
    "team_a_flag": "🇨🇭",
    "team_b": "Bosnia & Herzegovina",
    "team_b_code": "BA",
    "team_b_flag": "🇧🇦",
    "group": "Group B",
    "venue": "SoFi Stadium",
    "city": "Inglewood",
    "host_country": "USA"
  },
  {
    "match": 27,
    "date_utc": "2026-06-18",
    "kickoff_utc": "22:00",
    "kickoff_et": "6:00 PM",
    "team_a": "Canada",
    "team_a_code": "CA",
    "team_a_flag": "🇨🇦",
    "team_b": "Qatar",
    "team_b_code": "QA",
    "team_b_flag": "🇶🇦",
    "group": "Group B",
    "venue": "BC Place",
    "city": "Vancouver",
    "host_country": "Canada"
  },
  {
    "match": 28,
    "date_utc": "2026-06-19",
    "kickoff_utc": "01:00",
    "kickoff_et": "9:00 PM",
    "team_a": "Mexico",
    "team_a_code": "MX",
    "team_a_flag": "🇲🇽",
    "team_b": "South Korea",
    "team_b_code": "KR",
    "team_b_flag": "🇰🇷",
    "group": "Group A",
    "venue": "Estadio Akron",
    "city": "Guadalajara",
    "host_country": "Mexico"
  },
  {
    "match": 29,
    "date_utc": "2026-06-19",
    "kickoff_utc": "19:00",
    "kickoff_et": "3:00 PM",
    "team_a": "United States",
    "team_a_code": "US",
    "team_a_flag": "🇺🇸",
    "team_b": "Australia",
    "team_b_code": "AU",
    "team_b_flag": "🇦🇺",
    "group": "Group D",
    "venue": "Lumen Field",
    "city": "Seattle",
    "host_country": "USA"
  },
  {
    "match": 30,
    "date_utc": "2026-06-19",
    "kickoff_utc": "22:00",
    "kickoff_et": "6:00 PM",
    "team_a": "Scotland",
    "team_a_code": "SCO",
    "team_a_flag": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "team_b": "Morocco",
    "team_b_code": "MA",
    "team_b_flag": "🇲🇦",
    "group": "Group C",
    "venue": "Gillette Stadium",
    "city": "Foxborough",
    "host_country": "USA"
  },
  {
    "match": 31,
    "date_utc": "2026-06-20",
    "kickoff_utc": "00:30",
    "kickoff_et": "8:30 PM",
    "team_a": "Brazil",
    "team_a_code": "BR",
    "team_a_flag": "🇧🇷",
    "team_b": "Haiti",
    "team_b_code": "HT",
    "team_b_flag": "🇭🇹",
    "group": "Group C",
    "venue": "Lincoln Financial Field",
    "city": "Philadelphia",
    "host_country": "USA"
  },
  {
    "match": 32,
    "date_utc": "2026-06-20",
    "kickoff_utc": "03:00",
    "kickoff_et": "11:00 PM",
    "team_a": "Türkiye",
    "team_a_code": "TR",
    "team_a_flag": "🇹🇷",
    "team_b": "Paraguay",
    "team_b_code": "PY",
    "team_b_flag": "🇵🇾",
    "group": "Group D",
    "venue": "Levi's Stadium",
    "city": "Santa Clara",
    "host_country": "USA"
  },
  {
    "match": 33,
    "date_utc": "2026-06-20",
    "kickoff_utc": "17:00",
    "kickoff_et": "1:00 PM",
    "team_a": "Netherlands",
    "team_a_code": "NL",
    "team_a_flag": "🇳🇱",
    "team_b": "Sweden",
    "team_b_code": "SE",
    "team_b_flag": "🇸🇪",
    "group": "Group F",
    "venue": "NRG Stadium",
    "city": "Houston",
    "host_country": "USA"
  },
  {
    "match": 34,
    "date_utc": "2026-06-20",
    "kickoff_utc": "20:00",
    "kickoff_et": "4:00 PM",
    "team_a": "Germany",
    "team_a_code": "DE",
    "team_a_flag": "🇩🇪",
    "team_b": "Ivory Coast",
    "team_b_code": "CI",
    "team_b_flag": "🇨🇮",
    "group": "Group E",
    "venue": "BMO Field",
    "city": "Toronto",
    "host_country": "Canada"
  },
  {
    "match": 35,
    "date_utc": "2026-06-21",
    "kickoff_utc": "00:00",
    "kickoff_et": "8:00 PM",
    "team_a": "Ecuador",
    "team_a_code": "EC",
    "team_a_flag": "🇪🇨",
    "team_b": "Curaçao",
    "team_b_code": "CW",
    "team_b_flag": "🇨🇼",
    "group": "Group E",
    "venue": "Arrowhead Stadium",
    "city": "Kansas City",
    "host_country": "USA"
  },
  {
    "match": 36,
    "date_utc": "2026-06-21",
    "kickoff_utc": "04:00",
    "kickoff_et": "12:00 AM",
    "team_a": "Tunisia",
    "team_a_code": "TN",
    "team_a_flag": "🇹🇳",
    "team_b": "Japan",
    "team_b_code": "JP",
    "team_b_flag": "🇯🇵",
    "group": "Group F",
    "venue": "Estadio BBVA",
    "city": "Monterrey",
    "host_country": "Mexico"
  },
  {
    "match": 37,
    "date_utc": "2026-06-21",
    "kickoff_utc": "16:00",
    "kickoff_et": "12:00 PM",
    "team_a": "Spain",
    "team_a_code": "ES",
    "team_a_flag": "🇪🇸",
    "team_b": "Saudi Arabia",
    "team_b_code": "SA",
    "team_b_flag": "🇸🇦",
    "group": "Group H",
    "venue": "Mercedes-Benz Stadium",
    "city": "Atlanta",
    "host_country": "USA"
  },
  {
    "match": 38,
    "date_utc": "2026-06-21",
    "kickoff_utc": "19:00",
    "kickoff_et": "3:00 PM",
    "team_a": "Belgium",
    "team_a_code": "BE",
    "team_a_flag": "🇧🇪",
    "team_b": "Iran",
    "team_b_code": "IR",
    "team_b_flag": "🇮🇷",
    "group": "Group G",
    "venue": "SoFi Stadium",
    "city": "Inglewood",
    "host_country": "USA"
  },
  {
    "match": 39,
    "date_utc": "2026-06-21",
    "kickoff_utc": "22:00",
    "kickoff_et": "6:00 PM",
    "team_a": "Uruguay",
    "team_a_code": "UY",
    "team_a_flag": "🇺🇾",
    "team_b": "Cape Verde",
    "team_b_code": "CV",
    "team_b_flag": "🇨🇻",
    "group": "Group H",
    "venue": "Hard Rock Stadium",
    "city": "Miami Gardens",
    "host_country": "USA"
  },
  {
    "match": 40,
    "date_utc": "2026-06-22",
    "kickoff_utc": "01:00",
    "kickoff_et": "9:00 PM",
    "team_a": "New Zealand",
    "team_a_code": "NZ",
    "team_a_flag": "🇳🇿",
    "team_b": "Egypt",
    "team_b_code": "EG",
    "team_b_flag": "🇪🇬",
    "group": "Group G",
    "venue": "BC Place",
    "city": "Vancouver",
    "host_country": "Canada"
  },
  {
    "match": 41,
    "date_utc": "2026-06-22",
    "kickoff_utc": "17:00",
    "kickoff_et": "1:00 PM",
    "team_a": "Argentina",
    "team_a_code": "AR",
    "team_a_flag": "🇦🇷",
    "team_b": "Austria",
    "team_b_code": "AT",
    "team_b_flag": "🇦🇹",
    "group": "Group J",
    "venue": "AT&T Stadium",
    "city": "Arlington",
    "host_country": "USA"
  },
  {
    "match": 42,
    "date_utc": "2026-06-22",
    "kickoff_utc": "21:00",
    "kickoff_et": "5:00 PM",
    "team_a": "France",
    "team_a_code": "FR",
    "team_a_flag": "🇫🇷",
    "team_b": "Iraq",
    "team_b_code": "IQ",
    "team_b_flag": "🇮🇶",
    "group": "Group I",
    "venue": "Lincoln Financial Field",
    "city": "Philadelphia",
    "host_country": "USA"
  },
  {
    "match": 43,
    "date_utc": "2026-06-23",
    "kickoff_utc": "00:00",
    "kickoff_et": "8:00 PM",
    "team_a": "Norway",
    "team_a_code": "NO",
    "team_a_flag": "🇳🇴",
    "team_b": "Senegal",
    "team_b_code": "SN",
    "team_b_flag": "🇸🇳",
    "group": "Group I",
    "venue": "MetLife Stadium",
    "city": "East Rutherford",
    "host_country": "USA"
  },
  {
    "match": 44,
    "date_utc": "2026-06-23",
    "kickoff_utc": "03:00",
    "kickoff_et": "11:00 PM",
    "team_a": "Jordan",
    "team_a_code": "JO",
    "team_a_flag": "🇯🇴",
    "team_b": "Algeria",
    "team_b_code": "DZ",
    "team_b_flag": "🇩🇿",
    "group": "Group J",
    "venue": "Levi's Stadium",
    "city": "Santa Clara",
    "host_country": "USA"
  },
  {
    "match": 45,
    "date_utc": "2026-06-23",
    "kickoff_utc": "17:00",
    "kickoff_et": "1:00 PM",
    "team_a": "Portugal",
    "team_a_code": "PT",
    "team_a_flag": "🇵🇹",
    "team_b": "Uzbekistan",
    "team_b_code": "UZ",
    "team_b_flag": "🇺🇿",
    "group": "Group K",
    "venue": "NRG Stadium",
    "city": "Houston",
    "host_country": "USA"
  },
  {
    "match": 46,
    "date_utc": "2026-06-23",
    "kickoff_utc": "20:00",
    "kickoff_et": "4:00 PM",
    "team_a": "England",
    "team_a_code": "ENG",
    "team_a_flag": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "team_b": "Ghana",
    "team_b_code": "GH",
    "team_b_flag": "🇬🇭",
    "group": "Group L",
    "venue": "Gillette Stadium",
    "city": "Foxborough",
    "host_country": "USA"
  },
  {
    "match": 47,
    "date_utc": "2026-06-23",
    "kickoff_utc": "23:00",
    "kickoff_et": "7:00 PM",
    "team_a": "Panama",
    "team_a_code": "PA",
    "team_a_flag": "🇵🇦",
    "team_b": "Croatia",
    "team_b_code": "HR",
    "team_b_flag": "🇭🇷",
    "group": "Group L",
    "venue": "BMO Field",
    "city": "Toronto",
    "host_country": "Canada"
  },
  {
    "match": 48,
    "date_utc": "2026-06-24",
    "kickoff_utc": "02:00",
    "kickoff_et": "10:00 PM",
    "team_a": "Colombia",
    "team_a_code": "CO",
    "team_a_flag": "🇨🇴",
    "team_b": "DR Congo",
    "team_b_code": "CD",
    "team_b_flag": "🇨🇩",
    "group": "Group K",
    "venue": "Estadio Akron",
    "city": "Guadalajara",
    "host_country": "Mexico"
  },
  {
    "match": 49,
    "date_utc": "2026-06-24",
    "kickoff_utc": "19:00",
    "kickoff_et": "3:00 PM",
    "team_a": "Switzerland",
    "team_a_code": "CH",
    "team_a_flag": "🇨🇭",
    "team_b": "Canada",
    "team_b_code": "CA",
    "team_b_flag": "🇨🇦",
    "group": "Group B",
    "venue": "BC Place",
    "city": "Vancouver",
    "host_country": "Canada"
  },
  {
    "match": 50,
    "date_utc": "2026-06-24",
    "kickoff_utc": "19:00",
    "kickoff_et": "3:00 PM",
    "team_a": "Bosnia & Herzegovina",
    "team_a_code": "BA",
    "team_a_flag": "🇧🇦",
    "team_b": "Qatar",
    "team_b_code": "QA",
    "team_b_flag": "🇶🇦",
    "group": "Group B",
    "venue": "Lumen Field",
    "city": "Seattle",
    "host_country": "USA"
  },
  {
    "match": 51,
    "date_utc": "2026-06-24",
    "kickoff_utc": "22:00",
    "kickoff_et": "6:00 PM",
    "team_a": "Scotland",
    "team_a_code": "SCO",
    "team_a_flag": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "team_b": "Brazil",
    "team_b_code": "BR",
    "team_b_flag": "🇧🇷",
    "group": "Group C",
    "venue": "Hard Rock Stadium",
    "city": "Miami Gardens",
    "host_country": "USA"
  },
  {
    "match": 52,
    "date_utc": "2026-06-24",
    "kickoff_utc": "22:00",
    "kickoff_et": "6:00 PM",
    "team_a": "Morocco",
    "team_a_code": "MA",
    "team_a_flag": "🇲🇦",
    "team_b": "Haiti",
    "team_b_code": "HT",
    "team_b_flag": "🇭🇹",
    "group": "Group C",
    "venue": "Mercedes-Benz Stadium",
    "city": "Atlanta",
    "host_country": "USA"
  },
  {
    "match": 53,
    "date_utc": "2026-06-25",
    "kickoff_utc": "01:00",
    "kickoff_et": "9:00 PM",
    "team_a": "Czechia",
    "team_a_code": "CZ",
    "team_a_flag": "🇨🇿",
    "team_b": "Mexico",
    "team_b_code": "MX",
    "team_b_flag": "🇲🇽",
    "group": "Group A",
    "venue": "Estadio Azteca",
    "city": "Mexico City",
    "host_country": "Mexico"
  },
  {
    "match": 54,
    "date_utc": "2026-06-25",
    "kickoff_utc": "01:00",
    "kickoff_et": "9:00 PM",
    "team_a": "South Africa",
    "team_a_code": "ZA",
    "team_a_flag": "🇿🇦",
    "team_b": "South Korea",
    "team_b_code": "KR",
    "team_b_flag": "🇰🇷",
    "group": "Group A",
    "venue": "Estadio BBVA",
    "city": "Monterrey",
    "host_country": "Mexico"
  },
  {
    "match": 55,
    "date_utc": "2026-06-25",
    "kickoff_utc": "20:00",
    "kickoff_et": "4:00 PM",
    "team_a": "Curaçao",
    "team_a_code": "CW",
    "team_a_flag": "🇨🇼",
    "team_b": "Ivory Coast",
    "team_b_code": "CI",
    "team_b_flag": "🇨🇮",
    "group": "Group E",
    "venue": "Lincoln Financial Field",
    "city": "Philadelphia",
    "host_country": "USA"
  },
  {
    "match": 56,
    "date_utc": "2026-06-25",
    "kickoff_utc": "20:00",
    "kickoff_et": "4:00 PM",
    "team_a": "Ecuador",
    "team_a_code": "EC",
    "team_a_flag": "🇪🇨",
    "team_b": "Germany",
    "team_b_code": "DE",
    "team_b_flag": "🇩🇪",
    "group": "Group E",
    "venue": "MetLife Stadium",
    "city": "East Rutherford",
    "host_country": "USA"
  },
  {
    "match": 57,
    "date_utc": "2026-06-25",
    "kickoff_utc": "23:00",
    "kickoff_et": "7:00 PM",
    "team_a": "Japan",
    "team_a_code": "JP",
    "team_a_flag": "🇯🇵",
    "team_b": "Sweden",
    "team_b_code": "SE",
    "team_b_flag": "🇸🇪",
    "group": "Group F",
    "venue": "AT&T Stadium",
    "city": "Arlington",
    "host_country": "USA"
  },
  {
    "match": 58,
    "date_utc": "2026-06-25",
    "kickoff_utc": "23:00",
    "kickoff_et": "7:00 PM",
    "team_a": "Tunisia",
    "team_a_code": "TN",
    "team_a_flag": "🇹🇳",
    "team_b": "Netherlands",
    "team_b_code": "NL",
    "team_b_flag": "🇳🇱",
    "group": "Group F",
    "venue": "Arrowhead Stadium",
    "city": "Kansas City",
    "host_country": "USA"
  },
  {
    "match": 59,
    "date_utc": "2026-06-26",
    "kickoff_utc": "02:00",
    "kickoff_et": "10:00 PM",
    "team_a": "Türkiye",
    "team_a_code": "TR",
    "team_a_flag": "🇹🇷",
    "team_b": "United States",
    "team_b_code": "US",
    "team_b_flag": "🇺🇸",
    "group": "Group D",
    "venue": "SoFi Stadium",
    "city": "Inglewood",
    "host_country": "USA"
  },
  {
    "match": 60,
    "date_utc": "2026-06-26",
    "kickoff_utc": "02:00",
    "kickoff_et": "10:00 PM",
    "team_a": "Paraguay",
    "team_a_code": "PY",
    "team_a_flag": "🇵🇾",
    "team_b": "Australia",
    "team_b_code": "AU",
    "team_b_flag": "🇦🇺",
    "group": "Group D",
    "venue": "Levi's Stadium",
    "city": "Santa Clara",
    "host_country": "USA"
  },
  {
    "match": 61,
    "date_utc": "2026-06-26",
    "kickoff_utc": "19:00",
    "kickoff_et": "3:00 PM",
    "team_a": "Norway",
    "team_a_code": "NO",
    "team_a_flag": "🇳🇴",
    "team_b": "France",
    "team_b_code": "FR",
    "team_b_flag": "🇫🇷",
    "group": "Group I",
    "venue": "Gillette Stadium",
    "city": "Foxborough",
    "host_country": "USA"
  },
  {
    "match": 62,
    "date_utc": "2026-06-26",
    "kickoff_utc": "19:00",
    "kickoff_et": "3:00 PM",
    "team_a": "Senegal",
    "team_a_code": "SN",
    "team_a_flag": "🇸🇳",
    "team_b": "Iraq",
    "team_b_code": "IQ",
    "team_b_flag": "🇮🇶",
    "group": "Group I",
    "venue": "BMO Field",
    "city": "Toronto",
    "host_country": "Canada"
  },
  {
    "match": 63,
    "date_utc": "2026-06-27",
    "kickoff_utc": "00:00",
    "kickoff_et": "8:00 PM",
    "team_a": "Cape Verde",
    "team_a_code": "CV",
    "team_a_flag": "🇨🇻",
    "team_b": "Saudi Arabia",
    "team_b_code": "SA",
    "team_b_flag": "🇸🇦",
    "group": "Group H",
    "venue": "NRG Stadium",
    "city": "Houston",
    "host_country": "USA"
  },
  {
    "match": 64,
    "date_utc": "2026-06-27",
    "kickoff_utc": "00:00",
    "kickoff_et": "8:00 PM",
    "team_a": "Uruguay",
    "team_a_code": "UY",
    "team_a_flag": "🇺🇾",
    "team_b": "Spain",
    "team_b_code": "ES",
    "team_b_flag": "🇪🇸",
    "group": "Group H",
    "venue": "Estadio Akron",
    "city": "Guadalajara",
    "host_country": "Mexico"
  },
  {
    "match": 65,
    "date_utc": "2026-06-27",
    "kickoff_utc": "03:00",
    "kickoff_et": "11:00 PM",
    "team_a": "Egypt",
    "team_a_code": "EG",
    "team_a_flag": "🇪🇬",
    "team_b": "Iran",
    "team_b_code": "IR",
    "team_b_flag": "🇮🇷",
    "group": "Group G",
    "venue": "Lumen Field",
    "city": "Seattle",
    "host_country": "USA"
  },
  {
    "match": 66,
    "date_utc": "2026-06-27",
    "kickoff_utc": "03:00",
    "kickoff_et": "11:00 PM",
    "team_a": "New Zealand",
    "team_a_code": "NZ",
    "team_a_flag": "🇳🇿",
    "team_b": "Belgium",
    "team_b_code": "BE",
    "team_b_flag": "🇧🇪",
    "group": "Group G",
    "venue": "BC Place",
    "city": "Vancouver",
    "host_country": "Canada"
  },
  {
    "match": 67,
    "date_utc": "2026-06-27",
    "kickoff_utc": "21:00",
    "kickoff_et": "5:00 PM",
    "team_a": "Panama",
    "team_a_code": "PA",
    "team_a_flag": "🇵🇦",
    "team_b": "England",
    "team_b_code": "ENG",
    "team_b_flag": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "group": "Group L",
    "venue": "MetLife Stadium",
    "city": "East Rutherford",
    "host_country": "USA"
  },
  {
    "match": 68,
    "date_utc": "2026-06-27",
    "kickoff_utc": "21:00",
    "kickoff_et": "5:00 PM",
    "team_a": "Croatia",
    "team_a_code": "HR",
    "team_a_flag": "🇭🇷",
    "team_b": "Ghana",
    "team_b_code": "GH",
    "team_b_flag": "🇬🇭",
    "group": "Group L",
    "venue": "Lincoln Financial Field",
    "city": "Philadelphia",
    "host_country": "USA"
  },
  {
    "match": 69,
    "date_utc": "2026-06-27",
    "kickoff_utc": "23:30",
    "kickoff_et": "7:30 PM",
    "team_a": "Colombia",
    "team_a_code": "CO",
    "team_a_flag": "🇨🇴",
    "team_b": "Portugal",
    "team_b_code": "PT",
    "team_b_flag": "🇵🇹",
    "group": "Group K",
    "venue": "Hard Rock Stadium",
    "city": "Miami Gardens",
    "host_country": "USA"
  },
  {
    "match": 70,
    "date_utc": "2026-06-27",
    "kickoff_utc": "23:30",
    "kickoff_et": "7:30 PM",
    "team_a": "DR Congo",
    "team_a_code": "CD",
    "team_a_flag": "🇨🇩",
    "team_b": "Uzbekistan",
    "team_b_code": "UZ",
    "team_b_flag": "🇺🇿",
    "group": "Group K",
    "venue": "Mercedes-Benz Stadium",
    "city": "Atlanta",
    "host_country": "USA"
  },
  {
    "match": 71,
    "date_utc": "2026-06-28",
    "kickoff_utc": "02:00",
    "kickoff_et": "10:00 PM",
    "team_a": "Algeria",
    "team_a_code": "DZ",
    "team_a_flag": "🇩🇿",
    "team_b": "Austria",
    "team_b_code": "AT",
    "team_b_flag": "🇦🇹",
    "group": "Group J",
    "venue": "Arrowhead Stadium",
    "city": "Kansas City",
    "host_country": "USA"
  },
  {
    "match": 72,
    "date_utc": "2026-06-28",
    "kickoff_utc": "02:00",
    "kickoff_et": "10:00 PM",
    "team_a": "Jordan",
    "team_a_code": "JO",
    "team_a_flag": "🇯🇴",
    "team_b": "Argentina",
    "team_b_code": "AR",
    "team_b_flag": "🇦🇷",
    "group": "Group J",
    "venue": "AT&T Stadium",
    "city": "Arlington",
    "host_country": "USA"
  },
  {
    "match": 73,
    "date_utc": "2026-06-28",
    "kickoff_utc": "19:00",
    "kickoff_et": "3:00 PM",
    "team_a": "TBD",
    "team_a_code": "TBD",
    "team_a_flag": "",
    "team_b": "TBD",
    "team_b_code": "TBD",
    "team_b_flag": "",
    "group": "Round of 32",
    "venue": "SoFi Stadium",
    "city": "Inglewood",
    "host_country": "USA"
  },
  {
    "match": 74,
    "date_utc": "2026-06-29",
    "kickoff_utc": "17:00",
    "kickoff_et": "1:00 PM",
    "team_a": "TBD",
    "team_a_code": "TBD",
    "team_a_flag": "",
    "team_b": "TBD",
    "team_b_code": "TBD",
    "team_b_flag": "",
    "group": "Round of 32",
    "venue": "NRG Stadium",
    "city": "Houston",
    "host_country": "USA"
  },
  {
    "match": 75,
    "date_utc": "2026-06-29",
    "kickoff_utc": "20:30",
    "kickoff_et": "4:30 PM",
    "team_a": "TBD",
    "team_a_code": "TBD",
    "team_a_flag": "",
    "team_b": "TBD",
    "team_b_code": "TBD",
    "team_b_flag": "",
    "group": "Round of 32",
    "venue": "Gillette Stadium",
    "city": "Foxborough",
    "host_country": "USA"
  },
  {
    "match": 76,
    "date_utc": "2026-06-30",
    "kickoff_utc": "01:00",
    "kickoff_et": "9:00 PM",
    "team_a": "TBD",
    "team_a_code": "TBD",
    "team_a_flag": "",
    "team_b": "TBD",
    "team_b_code": "TBD",
    "team_b_flag": "",
    "group": "Round of 32",
    "venue": "Estadio BBVA",
    "city": "Monterrey",
    "host_country": "Mexico"
  },
  {
    "match": 77,
    "date_utc": "2026-06-30",
    "kickoff_utc": "17:00",
    "kickoff_et": "1:00 PM",
    "team_a": "TBD",
    "team_a_code": "TBD",
    "team_a_flag": "",
    "team_b": "TBD",
    "team_b_code": "TBD",
    "team_b_flag": "",
    "group": "Round of 32",
    "venue": "AT&T Stadium",
    "city": "Arlington",
    "host_country": "USA"
  },
  {
    "match": 78,
    "date_utc": "2026-06-30",
    "kickoff_utc": "21:00",
    "kickoff_et": "5:00 PM",
    "team_a": "TBD",
    "team_a_code": "TBD",
    "team_a_flag": "",
    "team_b": "TBD",
    "team_b_code": "TBD",
    "team_b_flag": "",
    "group": "Round of 32",
    "venue": "MetLife Stadium",
    "city": "East Rutherford",
    "host_country": "USA"
  },
  {
    "match": 79,
    "date_utc": "2026-07-01",
    "kickoff_utc": "01:00",
    "kickoff_et": "9:00 PM",
    "team_a": "TBD",
    "team_a_code": "TBD",
    "team_a_flag": "",
    "team_b": "TBD",
    "team_b_code": "TBD",
    "team_b_flag": "",
    "group": "Round of 32",
    "venue": "Estadio Azteca",
    "city": "Mexico City",
    "host_country": "Mexico"
  },
  {
    "match": 80,
    "date_utc": "2026-07-01",
    "kickoff_utc": "16:00",
    "kickoff_et": "12:00 PM",
    "team_a": "TBD",
    "team_a_code": "TBD",
    "team_a_flag": "",
    "team_b": "TBD",
    "team_b_code": "TBD",
    "team_b_flag": "",
    "group": "Round of 32",
    "venue": "Mercedes-Benz Stadium",
    "city": "Atlanta",
    "host_country": "USA"
  },
  {
    "match": 81,
    "date_utc": "2026-07-01",
    "kickoff_utc": "20:00",
    "kickoff_et": "4:00 PM",
    "team_a": "TBD",
    "team_a_code": "TBD",
    "team_a_flag": "",
    "team_b": "TBD",
    "team_b_code": "TBD",
    "team_b_flag": "",
    "group": "Round of 32",
    "venue": "Lumen Field",
    "city": "Seattle",
    "host_country": "USA"
  },
  {
    "match": 82,
    "date_utc": "2026-07-02",
    "kickoff_utc": "00:00",
    "kickoff_et": "8:00 PM",
    "team_a": "TBD",
    "team_a_code": "TBD",
    "team_a_flag": "",
    "team_b": "TBD",
    "team_b_code": "TBD",
    "team_b_flag": "",
    "group": "Round of 32",
    "venue": "Levi's Stadium",
    "city": "Santa Clara",
    "host_country": "USA"
  },
  {
    "match": 83,
    "date_utc": "2026-07-02",
    "kickoff_utc": "19:00",
    "kickoff_et": "3:00 PM",
    "team_a": "TBD",
    "team_a_code": "TBD",
    "team_a_flag": "",
    "team_b": "TBD",
    "team_b_code": "TBD",
    "team_b_flag": "",
    "group": "Round of 32",
    "venue": "SoFi Stadium",
    "city": "Inglewood",
    "host_country": "USA"
  },
  {
    "match": 84,
    "date_utc": "2026-07-02",
    "kickoff_utc": "23:00",
    "kickoff_et": "7:00 PM",
    "team_a": "TBD",
    "team_a_code": "TBD",
    "team_a_flag": "",
    "team_b": "TBD",
    "team_b_code": "TBD",
    "team_b_flag": "",
    "group": "Round of 32",
    "venue": "BMO Field",
    "city": "Toronto",
    "host_country": "Canada"
  },
  {
    "match": 85,
    "date_utc": "2026-07-03",
    "kickoff_utc": "03:00",
    "kickoff_et": "11:00 PM",
    "team_a": "TBD",
    "team_a_code": "TBD",
    "team_a_flag": "",
    "team_b": "TBD",
    "team_b_code": "TBD",
    "team_b_flag": "",
    "group": "Round of 32",
    "venue": "BC Place",
    "city": "Vancouver",
    "host_country": "Canada"
  },
  {
    "match": 86,
    "date_utc": "2026-07-03",
    "kickoff_utc": "18:00",
    "kickoff_et": "2:00 PM",
    "team_a": "TBD",
    "team_a_code": "TBD",
    "team_a_flag": "",
    "team_b": "TBD",
    "team_b_code": "TBD",
    "team_b_flag": "",
    "group": "Round of 32",
    "venue": "AT&T Stadium",
    "city": "Arlington",
    "host_country": "USA"
  },
  {
    "match": 87,
    "date_utc": "2026-07-03",
    "kickoff_utc": "22:00",
    "kickoff_et": "6:00 PM",
    "team_a": "TBD",
    "team_a_code": "TBD",
    "team_a_flag": "",
    "team_b": "TBD",
    "team_b_code": "TBD",
    "team_b_flag": "",
    "group": "Round of 32",
    "venue": "Hard Rock Stadium",
    "city": "Miami Gardens",
    "host_country": "USA"
  },
  {
    "match": 88,
    "date_utc": "2026-07-04",
    "kickoff_utc": "01:30",
    "kickoff_et": "9:30 PM",
    "team_a": "TBD",
    "team_a_code": "TBD",
    "team_a_flag": "",
    "team_b": "TBD",
    "team_b_code": "TBD",
    "team_b_flag": "",
    "group": "Round of 32",
    "venue": "Arrowhead Stadium",
    "city": "Kansas City",
    "host_country": "USA"
  },
  {
    "match": 89,
    "date_utc": "2026-07-04",
    "kickoff_utc": "17:00",
    "kickoff_et": "1:00 PM",
    "team_a": "TBD",
    "team_a_code": "TBD",
    "team_a_flag": "",
    "team_b": "TBD",
    "team_b_code": "TBD",
    "team_b_flag": "",
    "group": "Round of 16",
    "venue": "NRG Stadium",
    "city": "Houston",
    "host_country": "USA"
  },
  {
    "match": 90,
    "date_utc": "2026-07-04",
    "kickoff_utc": "21:00",
    "kickoff_et": "5:00 PM",
    "team_a": "TBD",
    "team_a_code": "TBD",
    "team_a_flag": "",
    "team_b": "TBD",
    "team_b_code": "TBD",
    "team_b_flag": "",
    "group": "Round of 16",
    "venue": "Lincoln Financial Field",
    "city": "Philadelphia",
    "host_country": "USA"
  },
  {
    "match": 91,
    "date_utc": "2026-07-05",
    "kickoff_utc": "20:00",
    "kickoff_et": "4:00 PM",
    "team_a": "TBD",
    "team_a_code": "TBD",
    "team_a_flag": "",
    "team_b": "TBD",
    "team_b_code": "TBD",
    "team_b_flag": "",
    "group": "Round of 16",
    "venue": "MetLife Stadium",
    "city": "East Rutherford",
    "host_country": "USA"
  },
  {
    "match": 92,
    "date_utc": "2026-07-06",
    "kickoff_utc": "00:00",
    "kickoff_et": "8:00 PM",
    "team_a": "TBD",
    "team_a_code": "TBD",
    "team_a_flag": "",
    "team_b": "TBD",
    "team_b_code": "TBD",
    "team_b_flag": "",
    "group": "Round of 16",
    "venue": "Estadio Azteca",
    "city": "Mexico City",
    "host_country": "Mexico"
  },
  {
    "match": 93,
    "date_utc": "2026-07-06",
    "kickoff_utc": "19:00",
    "kickoff_et": "3:00 PM",
    "team_a": "TBD",
    "team_a_code": "TBD",
    "team_a_flag": "",
    "team_b": "TBD",
    "team_b_code": "TBD",
    "team_b_flag": "",
    "group": "Round of 16",
    "venue": "AT&T Stadium",
    "city": "Arlington",
    "host_country": "USA"
  },
  {
    "match": 94,
    "date_utc": "2026-07-07",
    "kickoff_utc": "00:00",
    "kickoff_et": "8:00 PM",
    "team_a": "TBD",
    "team_a_code": "TBD",
    "team_a_flag": "",
    "team_b": "TBD",
    "team_b_code": "TBD",
    "team_b_flag": "",
    "group": "Round of 16",
    "venue": "Lumen Field",
    "city": "Seattle",
    "host_country": "USA"
  },
  {
    "match": 95,
    "date_utc": "2026-07-07",
    "kickoff_utc": "16:00",
    "kickoff_et": "12:00 PM",
    "team_a": "TBD",
    "team_a_code": "TBD",
    "team_a_flag": "",
    "team_b": "TBD",
    "team_b_code": "TBD",
    "team_b_flag": "",
    "group": "Round of 16",
    "venue": "Mercedes-Benz Stadium",
    "city": "Atlanta",
    "host_country": "USA"
  },
  {
    "match": 96,
    "date_utc": "2026-07-07",
    "kickoff_utc": "20:00",
    "kickoff_et": "4:00 PM",
    "team_a": "TBD",
    "team_a_code": "TBD",
    "team_a_flag": "",
    "team_b": "TBD",
    "team_b_code": "TBD",
    "team_b_flag": "",
    "group": "Round of 16",
    "venue": "BC Place",
    "city": "Vancouver",
    "host_country": "Canada"
  },
  {
    "match": 97,
    "date_utc": "2026-07-09",
    "kickoff_utc": "20:00",
    "kickoff_et": "4:00 PM",
    "team_a": "TBD",
    "team_a_code": "TBD",
    "team_a_flag": "",
    "team_b": "TBD",
    "team_b_code": "TBD",
    "team_b_flag": "",
    "group": "Quarter-final",
    "venue": "Gillette Stadium",
    "city": "Foxborough",
    "host_country": "USA"
  },
  {
    "match": 98,
    "date_utc": "2026-07-10",
    "kickoff_utc": "19:00",
    "kickoff_et": "3:00 PM",
    "team_a": "TBD",
    "team_a_code": "TBD",
    "team_a_flag": "",
    "team_b": "TBD",
    "team_b_code": "TBD",
    "team_b_flag": "",
    "group": "Quarter-final",
    "venue": "SoFi Stadium",
    "city": "Inglewood",
    "host_country": "USA"
  },
  {
    "match": 99,
    "date_utc": "2026-07-11",
    "kickoff_utc": "21:00",
    "kickoff_et": "5:00 PM",
    "team_a": "TBD",
    "team_a_code": "TBD",
    "team_a_flag": "",
    "team_b": "TBD",
    "team_b_code": "TBD",
    "team_b_flag": "",
    "group": "Quarter-final",
    "venue": "Hard Rock Stadium",
    "city": "Miami Gardens",
    "host_country": "USA"
  },
  {
    "match": 100,
    "date_utc": "2026-07-12",
    "kickoff_utc": "01:00",
    "kickoff_et": "9:00 PM",
    "team_a": "TBD",
    "team_a_code": "TBD",
    "team_a_flag": "",
    "team_b": "TBD",
    "team_b_code": "TBD",
    "team_b_flag": "",
    "group": "Quarter-final",
    "venue": "Arrowhead Stadium",
    "city": "Kansas City",
    "host_country": "USA"
  },
  {
    "match": 101,
    "date_utc": "2026-07-14",
    "kickoff_utc": "19:00",
    "kickoff_et": "3:00 PM",
    "team_a": "TBD",
    "team_a_code": "TBD",
    "team_a_flag": "",
    "team_b": "TBD",
    "team_b_code": "TBD",
    "team_b_flag": "",
    "group": "Semi-final",
    "venue": "AT&T Stadium",
    "city": "Arlington",
    "host_country": "USA"
  },
  {
    "match": 102,
    "date_utc": "2026-07-15",
    "kickoff_utc": "19:00",
    "kickoff_et": "3:00 PM",
    "team_a": "TBD",
    "team_a_code": "TBD",
    "team_a_flag": "",
    "team_b": "TBD",
    "team_b_code": "TBD",
    "team_b_flag": "",
    "group": "Semi-final",
    "venue": "Mercedes-Benz Stadium",
    "city": "Atlanta",
    "host_country": "USA"
  },
  {
    "match": 103,
    "date_utc": "2026-07-18",
    "kickoff_utc": "21:00",
    "kickoff_et": "5:00 PM",
    "team_a": "TBD",
    "team_a_code": "TBD",
    "team_a_flag": "",
    "team_b": "TBD",
    "team_b_code": "TBD",
    "team_b_flag": "",
    "group": "Third Place",
    "venue": "Hard Rock Stadium",
    "city": "Miami Gardens",
    "host_country": "USA"
  },
  {
    "match": 104,
    "date_utc": "2026-07-19",
    "kickoff_utc": "19:00",
    "kickoff_et": "3:00 PM",
    "team_a": "TBD",
    "team_a_code": "TBD",
    "team_a_flag": "",
    "team_b": "TBD",
    "team_b_code": "TBD",
    "team_b_flag": "",
    "group": "Final",
    "venue": "MetLife Stadium",
    "city": "East Rutherford",
    "host_country": "USA"
  }
]